	olive_std_core u0 (
		.clk_100m_clk           (<connected-to-clk_100m_clk>),           // clk_100m.clk
		.clk_40m_clk            (<connected-to-clk_40m_clk>),            //  clk_40m.clk
		.epcs_ss_n              (<connected-to-epcs_ss_n>),              //     epcs.ss_n
		.epcs_sclk              (<connected-to-epcs_sclk>),              //         .sclk
		.epcs_mosi              (<connected-to-epcs_mosi>),              //         .mosi
		.epcs_miso              (<connected-to-epcs_miso>),              //         .miso
		.hostuart_rxd           (<connected-to-hostuart_rxd>),           // hostuart.rxd
		.hostuart_txd           (<connected-to-hostuart_txd>),           //         .txd
		.i2c_scl                (<connected-to-i2c_scl>),                //      i2c.scl
		.i2c_scl_oe             (<connected-to-i2c_scl_oe>),             //         .scl_oe
		.i2c_sda                (<connected-to-i2c_sda>),                //         .sda
		.i2c_sda_oe             (<connected-to-i2c_sda_oe>),             //         .sda_oe
		.led_export             (<connected-to-led_export>),             //      led.export
		.nios2_cpu_resetrequest (<connected-to-nios2_cpu_resetrequest>), //    nios2.cpu_resetrequest
		.nios2_cpu_resettaken   (<connected-to-nios2_cpu_resettaken>),   //         .cpu_resettaken
		.pfcif_pfc_clk          (<connected-to-pfcif_pfc_clk>),          //    pfcif.pfc_clk
		.pfcif_pfc_reset        (<connected-to-pfcif_pfc_reset>),        //         .pfc_reset
		.pfcif_cmd              (<connected-to-pfcif_cmd>),              //         .cmd
		.pfcif_resp             (<connected-to-pfcif_resp>),             //         .resp
		.reset_reset_n          (<connected-to-reset_reset_n>),          //    reset.reset_n
		.sdr_addr               (<connected-to-sdr_addr>),               //      sdr.addr
		.sdr_ba                 (<connected-to-sdr_ba>),                 //         .ba
		.sdr_cas_n              (<connected-to-sdr_cas_n>),              //         .cas_n
		.sdr_cke                (<connected-to-sdr_cke>),                //         .cke
		.sdr_cs_n               (<connected-to-sdr_cs_n>),               //         .cs_n
		.sdr_dq                 (<connected-to-sdr_dq>),                 //         .dq
		.sdr_dqm                (<connected-to-sdr_dqm>),                //         .dqm
		.sdr_ras_n              (<connected-to-sdr_ras_n>),              //         .ras_n
		.sdr_we_n               (<connected-to-sdr_we_n>),               //         .we_n
		.servo_pwm              (<connected-to-servo_pwm>),              //    servo.pwm
		.servo_dsm              (<connected-to-servo_dsm>),              //         .dsm
		.spi_ss_n               (<connected-to-spi_ss_n>),               //      spi.ss_n
		.spi_sclk               (<connected-to-spi_sclk>),               //         .sclk
		.spi_mosi               (<connected-to-spi_mosi>),               //         .mosi
		.spi_miso               (<connected-to-spi_miso>),               //         .miso
		.uart0_rxd              (<connected-to-uart0_rxd>),              //    uart0.rxd
		.uart0_txd              (<connected-to-uart0_txd>),              //         .txd
		.uart0_cts_n            (<connected-to-uart0_cts_n>),            //         .cts_n
		.uart0_rts_n            (<connected-to-uart0_rts_n>),            //         .rts_n
		.uart1_rxd              (<connected-to-uart1_rxd>),              //    uart1.rxd
		.uart1_txd              (<connected-to-uart1_txd>),              //         .txd
		.uart1_cts_n            (<connected-to-uart1_cts_n>),            //         .cts_n
		.uart1_rts_n            (<connected-to-uart1_rts_n>)             //         .rts_n
	);

